import unittest
import xml.etree.ElementTree as ET
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PLUGIN_DIR = ROOT / "gma2" / "plugins"
MA_NAMESPACE = "http://schemas.malighting.de/grandma2/xml/MA"


class GrandMA2PluginPackageTests(unittest.TestCase):
    def test_ma2_39_plugin_descriptor_references_paired_lua_with_exact_case(self):
        xml_path = PLUGIN_DIR / "ZEN_AGENT.xml"
        lua_path = PLUGIN_DIR / "ZEN_AGENT.lua"
        root = ET.parse(xml_path).getroot()
        self.assertEqual(root.tag, f"{{{MA_NAMESPACE}}}MA")
        self.assertEqual((root.attrib["major_vers"], root.attrib["minor_vers"], root.attrib["stream_vers"]), ("3", "9", "60"))
        self.assertIn("/3.9.60/MA.xsd", root.attrib["{http://www.w3.org/2001/XMLSchema-instance}schemaLocation"])
        plugin = root.find(f"{{{MA_NAMESPACE}}}Plugin")
        self.assertIsNotNone(plugin)
        self.assertEqual(plugin.attrib, {"index": "0", "execute_on_load": "0", "name": "ZEN_AGENT", "luafile": "ZEN_AGENT.lua"})
        self.assertTrue(lua_path.is_file())
        self.assertEqual(lua_path.name, plugin.attrib["luafile"])

    def test_ma2_lua_entrypoint_uses_the_read_only_mailbox_protocol(self):
        lua = (PLUGIN_DIR / "ZEN_AGENT.lua").read_text(encoding="utf-8")
        portable_lua = (ROOT / "lua" / "ZEN_AGENT.lua").read_text(encoding="utf-8")
        self.assertEqual(lua, portable_lua)
        self.assertIn("local function main()", lua)
        self.assertIn("return main", lua)
        self.assertIn('gma.user.getvar("ZEN_AGENT_REQUEST")', lua)
        self.assertIn('gma.feedback("ZEN_DEBUG|REQUEST|" .. tostring(request))', lua)
        self.assertIn('gma.user.setvar("ZEN_AGENT_REQUEST", "")', lua)
        self.assertIn('tostring(request):match("^%s*(.-)%s*$")', lua)
        self.assertIn('normalized:match("^([A-Za-z0-9_-]+)%s+([a-z_]+)%s*(.-)%s*$")', lua)
        self.assertIn('feedback(visible_request_id, "ERROR", "MALFORMED_REQUEST")', lua)
        self.assertIn('argument == ""', lua)
        self.assertNotIn(')|([a-z_]+)|', lua)
        self.assertIn('"ZEN_STATE|" .. request_id', lua)
        self.assertIn('"DUPLICATE_REQUEST"', lua)
        self.assertIn('"MALFORMED_REQUEST"', lua)
        self.assertIn('"UNKNOWN_COMMAND"', lua)
        self.assertIn('command == "group_membership"', lua)
        self.assertIn('command == "object_probe"', lua)
        self.assertIn('command == "fixture_property_probe"', lua)
        self.assertIn('command == "layout_fixture_probe"', lua)
        self.assertIn('command == "preset_probe"', lua)
        self.assertIn('command == "preset_context_probe"', lua)
        self.assertIn('ZEN_PRESET_PROBE|', lua)
        self.assertIn('command == "selection_probe"', lua)
        self.assertIn('command == "programmer_probe"', lua)
        self.assertIn('ZEN_INSPECT_PROBE|', lua)
        self.assertIn('inspect_show_object(request_id, "selection", "Selection")', lua)
        self.assertIn('inspect_show_object(request_id, "programmer", "Programmer")', lua)
        self.assertIn('gma.user.getcmddest', lua)
        self.assertIn('gma.user.getselectedexec', lua)
        self.assertIn('argument:match("^(Preset)%s+([1-9][0-9]*%.[1-9][0-9]*)$")', lua)
        self.assertIn('argument:match("^(Group)%s+([1-9][0-9]*)$")', lua)
        self.assertIn('argument:match("^(Fixture)%s+([1-9][0-9]*)$")', lua)
        self.assertIn('argument:match("^(Subfixture)%s+([1-9][0-9]*)$")', lua)
        self.assertIn('argument:match("^(Macro)%s+([1-9][0-9]*)$")', lua)
        self.assertIn('argument:match("^(Executor)%s+([1-9][0-9]*%.[1-9][0-9]*)$")', lua)
        self.assertIn('argument:match("^(Sequence)%s+([1-9][0-9]*)$")', lua)
        self.assertIn('argument:match("^(Effect)%s+([1-9][0-9]*)$")', lua)
        self.assertIn('gma.show.getobj.class, object_handle', lua)
        self.assertIn('gma.show.getobj.number, object_handle', lua)
        self.assertIn('gma.show.getobj.name, object_handle', lua)
        self.assertIn('ZEN_LAYOUT_PROBE|', lua)
        self.assertIn('ZEN_LAYOUT_FIXTURE_PROBE|', lua)
        self.assertIn('ZEN_FIXTURE_PROBE|', lua)
        self.assertIn('gma.show.getobj.child, node, child_index', lua)
        self.assertIn('gma.show.getobj.parent, node', lua)
        self.assertIn('if depth >= 2 then return end', lua)
        self.assertIn('math.min(child_count, 12)', lua)
        self.assertIn('math.min(tonumber(safely(gma.show.property.amount, node) or 0) or 0, 16)', lua)
        self.assertIn('debug("GROUP_HANDLE", group)', lua)
        self.assertIn('debug("CLASS", safely(gma.show.getobj.class, group))', lua)
        self.assertIn('debug("AMOUNT", amount)', lua)
        self.assertIn('debug("PROP_AMOUNT", property_amount)', lua)
        self.assertIn('gma.show.property.name, group, property_index', lua)
        self.assertIn('gma.show.property.get, group, property_index', lua)
        self.assertIn('debug("PROP", tostring(property_index)', lua)
        self.assertIn('"UNSUPPORTED_SAFE_ACCESS"', lua)
        for forbidden in ("gma.cmd", "Store", "Update", "Delete", "Clone", "Patch", "ClearSelection"):
            self.assertNotIn(forbidden, lua)
        self.assertNotIn("main(display_handle, argument)", lua)
        readme = (PLUGIN_DIR / "README.txt").read_text(encoding="utf-8")
        self.assertIn("ZEN_AGENT.xml", readme)
        self.assertIn("ZEN_AGENT.lua", readme)
        self.assertIn('SetUserVar $ZEN_AGENT_REQUEST="abc123 group_membership 1"', readme)
        self.assertIn("Plugin 3", readme)
        self.assertIn("ZEN_DEBUG|GROUP_HANDLE", readme)
        self.assertIn("UNSUPPORTED_SAFE_ACCESS", readme)
        self.assertIn("import `ZEN_AGENT.xml` again", readme)
        self.assertIn('object_probe Preset 1.1', readme)
        self.assertIn('object_probe Group 1', readme)
        self.assertIn('object_probe Fixture 1', readme)
        self.assertIn('object_probe Subfixture 1', readme)
        self.assertIn('object_probe Macro 1', readme)
        self.assertIn('object_probe Executor 1.1', readme)
        self.assertIn('object_probe Sequence 1', readme)
        self.assertIn('object_probe Effect 1', readme)
        self.assertIn('layout_fixture_probe 99', readme)
        self.assertIn('selection_probe', readme)
        self.assertIn('programmer_probe', readme)


if __name__ == "__main__":
    unittest.main()
